### ISSUE TITLE
Epic Stack example with Hanko

### ISSUE THREAD

**Issue by FlxMgdnz** [teamhanko/hanko#931]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Description

As Epic Stack only provides very basic auth, the integration with Hanko should be helpful for some users.

`epic-stack-with-hanko`

https://www.epicweb.dev/epic-stack
https://github.com/epicweb-dev/epic-stack/blob/main/docs/examples.md

### Describe your ideal solution

An integration of Hanko with Epic Stack and a PR on Epic Stack with that example.

### Hanko Version

0.8.0

**Comment by jemiluv8** [comment]
/attempt #93
Seems interesting @FlxMgdnz can you assign this to me?

**Comment by jemiluv8** [comment]
### My Approach
I'm looking to make login with hanko to be similar to social login.
It is just another option available to people who may want to sign up.

Ultimately, it just plugs into the existing auth for epic start with minor
modifications to onboarding, logout and profile screens

I've created a repositorory at https://github.com/jemiluv8/epic-stack-with-hanko
for the example with hanko. Below is a loom video of my approach thus far.

https://www.loom.com/share/c784990e924347f7931d95b15da7951b

### Next Steps
- [ ] Complete the example - ensuring feature parity with existing frontend guides at least
- [ ] Add the example to the epic-stack documentation and create a PR
- [ ] Write documentation(in hanko) for the example in the docs for frontend-guides

**Comment by FlxMgdnz** [comment]
Hey, thanks a lot for this suggestion. Unfortunately, I don't think this kind of integration of Hanko into Epic Stack makes much sense. Instead, Hanko would have to be the primary login provider, which means replacing most of the authentication code in Epic Stack.

On second thought, though, it's questionable whether we should really do that. For Epic Stack, it would probably be better to just add passkey functionality and keep everything else in place.

As it happens, we are working on a passkey API for exactly this purpose, however it is not yet available.

I suggest that we pause this task and start a new attempt when the passkey API is ready. Apologies.
